language: bash

services:
  - docker

env:
  - REPO=fabricepipart/all-in-one-build-image

script:
  - docker build -t $REPO:$TRAVIS_COMMIT .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:latest
  - docker push $REPO:$TRAVIS_COMMIT
  - docker push $REPO:latest
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:$TRAVIS_BRANCH && docker push $REPO:$TRAVIS_BRANCH; else true ; fi
  - docker logout