language: bash

services:
  - docker

env:
  - REPO=fabricepipart/all-in-one-build-image

script:
  - docker build -t $REPO:$TRAVIS_COMMIT .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $REPO:$COMMIT $REPO:ci-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - docker logout